run:
  timeout: "3m"
  issue-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  skip-files:
    - pkg/dgvoice/.*.go$
    - pkg/speech/win32/.*.go$
  go: "1.19"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - godot
    - forbidigo
    - gocritic
    - revive
    - gofmt
