volumes:
  dbData:
    driver: local
services:
  ceviord:
    image: ghcr.io/azuki-bar/ceviord:main-055a1c1c-1654485989
    environment:
      CEVIORD_CONN_DISCORD: ""
      CEVIORD_CONN_CEVIO_TOKEN: ""
      CEVIORD_CONN_CEVIO_END_POINT: "example.com:12345"
      CEVIORD_CONN_DB_NAME: "mysql"
      CEVIORD_CONN_DB_ADDR: "db"
      CEVIORD_CONN_DB_PORT: "3306"
      CEVIORD_CONN_DB_PASSWORD: "password"
      CEVIORD_CONN_DB_USER: "root"
      CEVIORD_CONN_DB_PROTOCOL: "tcp"
    restart: on-failure
  db:
    image: mysql:8.0.41-debian
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbData:/var/lib/mysql
    ports:
      - 33060:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
