volumes:
  dbdata:
    driver: local
services:
  ceviord:
    build:
      dockerfile: ./Dockerfile
    environment:
      CEVIORD_CONN_DISCORD: ""
      CEVIORD_CONN_CEVIO_TOKEN: ""
      CEVIORD_CONN_CEVIO_END_POINT: ""
      CEVIORD_CONN_DSN: "root:password@tcp(db:3306)/mysql"
      CEVIORD_CONN_DRIVER_NAME: "mysql"
    depends_on:
      - db
  db:
    image: mysql:8.0.28-debian
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql