// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: proto/textToSpeech.proto

package spec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TtsClient is the client API for Tts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TtsClient interface {
	CreateWav(ctx context.Context, in *CevioTtsRequest, opts ...grpc.CallOption) (*CevioTtsResponse, error)
}

type ttsClient struct {
	cc grpc.ClientConnInterface
}

func NewTtsClient(cc grpc.ClientConnInterface) TtsClient {
	return &ttsClient{cc}
}

func (c *ttsClient) CreateWav(ctx context.Context, in *CevioTtsRequest, opts ...grpc.CallOption) (*CevioTtsResponse, error) {
	out := new(CevioTtsResponse)
	err := c.cc.Invoke(ctx, "/Tts/CreateWav", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TtsServer is the server API for Tts service.
// All implementations must embed UnimplementedTtsServer
// for forward compatibility
type TtsServer interface {
	CreateWav(context.Context, *CevioTtsRequest) (*CevioTtsResponse, error)
	mustEmbedUnimplementedTtsServer()
}

// UnimplementedTtsServer must be embedded to have forward compatible implementations.
type UnimplementedTtsServer struct {
}

func (UnimplementedTtsServer) CreateWav(context.Context, *CevioTtsRequest) (*CevioTtsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWav not implemented")
}
func (UnimplementedTtsServer) mustEmbedUnimplementedTtsServer() {}

// UnsafeTtsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TtsServer will
// result in compilation errors.
type UnsafeTtsServer interface {
	mustEmbedUnimplementedTtsServer()
}

func RegisterTtsServer(s grpc.ServiceRegistrar, srv TtsServer) {
	s.RegisterService(&Tts_ServiceDesc, srv)
}

func _Tts_CreateWav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CevioTtsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TtsServer).CreateWav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tts/CreateWav",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TtsServer).CreateWav(ctx, req.(*CevioTtsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tts_ServiceDesc is the grpc.ServiceDesc for Tts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tts",
	HandlerType: (*TtsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWav",
			Handler:    _Tts_CreateWav_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/textToSpeech.proto",
}
