// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: proto/textToSpeech.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CevioTtsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text     string            `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Cast     string            `protobuf:"bytes,2,opt,name=cast,proto3" json:"cast,omitempty"`
	Volume   uint32            `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Speed    uint32            `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Pitch    uint32            `protobuf:"varint,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Alpha    uint32            `protobuf:"varint,6,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Intro    uint32            `protobuf:"varint,7,opt,name=intro,proto3" json:"intro,omitempty"`
	Emotions map[string]uint32 `protobuf:"bytes,8,rep,name=emotions,proto3" json:"emotions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Token    string            `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CevioTtsRequest) Reset() {
	*x = CevioTtsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_textToSpeech_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CevioTtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CevioTtsRequest) ProtoMessage() {}

func (x *CevioTtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_textToSpeech_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CevioTtsRequest.ProtoReflect.Descriptor instead.
func (*CevioTtsRequest) Descriptor() ([]byte, []int) {
	return file_proto_textToSpeech_proto_rawDescGZIP(), []int{0}
}

func (x *CevioTtsRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CevioTtsRequest) GetCast() string {
	if x != nil {
		return x.Cast
	}
	return ""
}

func (x *CevioTtsRequest) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *CevioTtsRequest) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *CevioTtsRequest) GetPitch() uint32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *CevioTtsRequest) GetAlpha() uint32 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *CevioTtsRequest) GetIntro() uint32 {
	if x != nil {
		return x.Intro
	}
	return 0
}

func (x *CevioTtsRequest) GetEmotions() map[string]uint32 {
	if x != nil {
		return x.Emotions
	}
	return nil
}

func (x *CevioTtsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CevioTtsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audio []byte `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
}

func (x *CevioTtsResponse) Reset() {
	*x = CevioTtsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_textToSpeech_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CevioTtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CevioTtsResponse) ProtoMessage() {}

func (x *CevioTtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_textToSpeech_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CevioTtsResponse.ProtoReflect.Descriptor instead.
func (*CevioTtsResponse) Descriptor() ([]byte, []int) {
	return file_proto_textToSpeech_proto_rawDescGZIP(), []int{1}
}

func (x *CevioTtsResponse) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

var File_proto_textToSpeech_proto protoreflect.FileDescriptor

var file_proto_textToSpeech_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70,
	0x65, 0x65, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x02, 0x0a, 0x0f, 0x43,
	0x65, 0x76, 0x69, 0x6f, 0x54, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x74, 0x63, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x69, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x3a, 0x0a, 0x08, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x43, 0x65, 0x76, 0x69, 0x6f,
	0x54, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x3b, 0x0a, 0x0d, 0x45, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x28, 0x0a, 0x10, 0x43, 0x65, 0x76, 0x69, 0x6f, 0x54, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x32,
	0x39, 0x0a, 0x03, 0x54, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x61, 0x76, 0x12, 0x10, 0x2e, 0x43, 0x65, 0x76, 0x69, 0x6f, 0x54, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x43, 0x65, 0x76, 0x69, 0x6f, 0x54, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f,
	0x73, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_textToSpeech_proto_rawDescOnce sync.Once
	file_proto_textToSpeech_proto_rawDescData = file_proto_textToSpeech_proto_rawDesc
)

func file_proto_textToSpeech_proto_rawDescGZIP() []byte {
	file_proto_textToSpeech_proto_rawDescOnce.Do(func() {
		file_proto_textToSpeech_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_textToSpeech_proto_rawDescData)
	})
	return file_proto_textToSpeech_proto_rawDescData
}

var file_proto_textToSpeech_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_textToSpeech_proto_goTypes = []interface{}{
	(*CevioTtsRequest)(nil),  // 0: CevioTtsRequest
	(*CevioTtsResponse)(nil), // 1: CevioTtsResponse
	nil,                      // 2: CevioTtsRequest.EmotionsEntry
}
var file_proto_textToSpeech_proto_depIdxs = []int32{
	2, // 0: CevioTtsRequest.emotions:type_name -> CevioTtsRequest.EmotionsEntry
	0, // 1: Tts.CreateWav:input_type -> CevioTtsRequest
	1, // 2: Tts.CreateWav:output_type -> CevioTtsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_textToSpeech_proto_init() }
func file_proto_textToSpeech_proto_init() {
	if File_proto_textToSpeech_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_textToSpeech_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CevioTtsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_textToSpeech_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CevioTtsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_textToSpeech_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_textToSpeech_proto_goTypes,
		DependencyIndexes: file_proto_textToSpeech_proto_depIdxs,
		MessageInfos:      file_proto_textToSpeech_proto_msgTypes,
	}.Build()
	File_proto_textToSpeech_proto = out.File
	file_proto_textToSpeech_proto_rawDesc = nil
	file_proto_textToSpeech_proto_goTypes = nil
	file_proto_textToSpeech_proto_depIdxs = nil
}
