name: build and test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.50.1
          args: --timeout 3m
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run Go build
        run: |-
          go build ./...

      - name: Run Go Test
        run: |-
          go test -v ./...
